"""VoteImage 추가

Revision ID: 9e2715d6e171
Revises: 0fdb97db69f3
Create Date: 2025-01-17 03:22:31.557304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e2715d6e171'
down_revision: Union[str, None] = '0fdb97db69f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vote_image',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('vote_id', sa.BigInteger(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('src', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['vote_id'], ['vote.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vote_image')
    # ### end Alembic commands ###
