"""Comment에 edit 관련 필드 추가하고, created_datetime과 edited_datetime Timestamp로 변경

Revision ID: 4fa11f1eada9
Revises: 0a5a02cfb40b
Create Date: 2025-01-13 22:34:30.920243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4fa11f1eada9'
down_revision: Union[str, None] = '0a5a02cfb40b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('is_edited', sa.Boolean(), nullable=False))
    op.add_column('comment', sa.Column('edited_datetime', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('vote', 'create_datetime',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('vote', 'end_datetime',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vote', 'end_datetime',
               existing_type=sa.DateTime(timezone=True),
               type_=mysql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('vote', 'create_datetime',
               existing_type=sa.DateTime(timezone=True),
               type_=mysql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('comment', 'edited_datetime')
    op.drop_column('comment', 'is_edited')
    # ### end Alembic commands ###
