"""appended User Table

Revision ID: 69e6f0a92334
Revises: 33dee95fb8e9
Create Date: 2025-01-01 19:06:20.796620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '69e6f0a92334'
down_revision: Union[str, None] = '33dee95fb8e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(length=20), nullable=False))
    op.add_column('user', sa.Column('college', sa.Integer(), nullable=False))
    op.alter_column('user', 'id',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('user', 'college')
    op.drop_column('user', 'name')
    # ### end Alembic commands ###
